# Generated by Django 6.0 on 2026-01-29 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='desc',
            new_name='msg_text',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Menssagem'), ('user_type', 'Usuários'), ('folder_type', 'Pastas'), ('team_type', 'Equipes')], default='message', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_to',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
