# Generated by Django 6.0 on 2026-02-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_desc_notification_msg_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='main_folder',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
