# Generated by Django 6.0 on 2026-02-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_main_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='main_folder',
        ),
    ]
