# Generated by Django 6.0 on 2026-01-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
