# Generated by Django 6.0.3 on 2026-03-15 00:31

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive',
            field=models.FileField(storage=storage.models.OverwriteStorage(), upload_to=storage.models.archive_upload_path),
        ),
    ]
