# Generated by Django 6.0 on 2026-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_archive_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive',
            field=models.FileField(upload_to='main/'),
        ),
    ]
