# Generated by Django 6.0 on 2026-02-06 18:41

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_archive_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive',
            field=models.FileField(storage=storage.models.OverwriteStorage(), upload_to='main/'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
    ]
