# Generated by Django 6.0 on 2026-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_archive_archive_alter_archive_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
