# Generated by Django 6.0 on 2026-02-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_archive_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
