# Generated by Django 6.0 on 2026-02-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_folder_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_path',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
