# Generated by Django 6.0 on 2026-02-10 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_folder_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='folder_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage.folder'),
            preserve_default=False,
        ),
    ]
