# Generated by Django 6.0 on 2026-02-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_archive_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.team'),
        ),
    ]
